#!/usr/bin/env bash
# A Bash script that configures a new Ubuntu machine with the requirements:
#+ Install nginx
#+ Nginx should be listening on port 80
#+ When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Holberton School

sudo apt-get -y install nginx
sudo service nginx start
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html 
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx reload
