#!/usr/bin/env bash
# Configure a new Nginx server with a custom 404 page
#+ that contains the string Ceci n'est pas une page.

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start

#redirection
newlines="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "26i $newlines" /etc/nginx/sites-available/default

#error 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/index.nginx-debian.html
newlines="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sudo sed -i "27i $newlines" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
