#!/usr/bin/env bash
# Configure a new Nginx server with a custom 404 page
#+ that contains the string Ceci n'est pas une page.

sudo apt-get -y update
sudo apt-get -y install nginx

#custom error 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html
newlines="\\\terror_page 404 /error404.html;\n\tlocation = /error404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "27i $newlines" /etc/nginx/sites-available/default

# restart nginx server
sudo service nginx restart

