#!/usr/bin/env bash
# A Bash script that configures a new Ubuntu machine with the requirements:
#+ configure web-02 to be identical to web-01
#+ Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02
#+ The name of the custom HTTP header must be X-Served-By
#+ The value of the custom HTTP header must be the hostname of the server Nginx is running on
#+ Ignore SC2154 for shellcheck

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a add_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default
sudo service nginx start
