#!/usr/bin/env bash
# prints numbers from 1 to 100
# prints FizzBuzz when the number is a multiple of 3 and 5
# prints Fizz when the number is multiple of 3
# prints Buzz when the number is a multiple of 5
# Otherwise, displays the number

i=1
while [ $i -le 100 ]
do
	if [ $((i % 5)) -eq 0 ] && [ $((i % 3)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((i % 5)) -eq 0 ]
	then
		echo "Buzz"
	elif [ $((i % 3)) -eq 0 ]
	then
		echo "Fizz"
	else
		echo $i
	fi
		i=$((i + 1))
done
