#!/usr/bin/env bash
# prints information about a file "holbertonschool"

file="holbertonschool"
if [ -e "$file" ]
then
    echo "$file file exists"
    if [ -s "$file" ]
    then
        echo "holbertonschool file is not empty"
    else
        echo "holbertonschool file is empty"
    fi
    if [ -f "$file" ]
    then
        echo "holbertonschool is a regular file"
    fi
else
    echo "$file file does not exist"
fi